name: CI

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - photon-style
      - proton-style
    paths:
      - userChrome.css
      - userContent.css
      - css/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node cache
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Package Install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
